food_dropship_analytics:
  outputs:
    dev:
      dbname: db
      host: postgres
      pass: db_password
      port: 5432
      schema: dev
      threads: 4
      type: postgres
      user: db_user
  target: dev
