version: 2

models:
  - name: stg_posthog_events
    tests: []
    columns:
      - name: user_id
        tests: [not_null]
      - name: event_time
        tests: [not_null]
      - name: event_standard
        tests:
          - accepted_values:
              values: ['homepage_view','product_view','add_to_cart','checkout_started','purchase','other']

  - name: fact_orders
    columns:
      - name: order_id
        tests: 
          - unique: {}
          - not_null: {}
      - name: order_revenue
        tests: 
          - not_null: {}