name: "food_dropship_analytics"
version: "1.0.0"
config-version: 2
profile: "food_dropship_analytics"

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

# Create schemas on run and keep things reproducible
on-run-start:
  - "create schema if not exists raw"
  - "create schema if not exists staging"
  - "create schema if not exists core"
  - "create schema if not exists marts"

models:
  food_dropship_analytics:
    +materialized: view

    staging:
      +schema: staging
      +materialized: view

    core:
      +schema: core
      # we want performant tables here
      +materialized: table

    marts:
      +schema: marts
      +materialized: table
